DROP DATABASE IF EXISTS `PremisesPal`;
CREATE DATABASE `PremisesPal`;
USE `PremisesPal`;

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT
(
	email		VARCHAR(50)	NOT NULL,
    pass		VARCHAR(25)	NOT NULL,
    biography	VARCHAR(200),
    
    PRIMARY KEY (email),
);

DROP TABLE IF EXISTS ACCOUNT_SPECIALTIES;
CREATE TABLE ACCOUNT_SPECIALTIES
(
	email		VARCHAR(50),
    specialty	VARCHAR(25),
    
    FOREIGN KEY (email) REFERENCES ACCOUNT(email),
);

DROP TABLE IF EXISTS ACCOUNT_REFERENCES;
CREATE TABLE ACCOUNT_REFERENCES
(
	email		VARCHAR(50),
    reference	VARCHAR(25),
    
    FOREIGN KEY (email) REFERENCES ACCOUNT(email),
);

DROP TABLE IF EXISTS ACCOUNT_REVIEWS;
CREATE TABLE ACCOUNT_REVIEWS
(
	email		VARCHAR(50),
    review		VARCHAR(25),
    
    FOREIGN KEY (email) REFERENCES ACCOUNT(email),
);


DROP TABLE IF EXISTS POST;
CREATE TABLE POST
(
	post_id		INT AUTO_INCREMENT,
    email		VARCHAR(50),
	price		FLOAT,
    dateOfPosting	VARCHAR(100),
	location	VARCHAR(100),
    description	VARCHAR(500),
    requiredSkills	VARCHAR(100),
    
    FOREIGN KEY (email) REFERENCES ACCOUNT(email),
);
